/* Local learning evidence, not visitor tracking. Only checked answers and explicit self-ratings. */
window.VamosAdaptive={create(api){
 'use strict';
 const {data,state,save}=api;
 const skills=['listening','meaning','order','recall','situation'];
 const all=new Map(data.expanded.lessons.flatMap(l=>l.examples.map(p=>[p.audio,{...p,day:l.day}])));
 const cleanMetric=v=>({attempts:Math.min(10000,Math.max(0,Number(v?.attempts)||0)),misses:Math.min(10000,Math.max(0,Number(v?.misses)||0)),aided:Math.min(10000,Math.max(0,Number(v?.aided)||0)),last:Math.min(Date.now(),Math.max(0,Number(v?.last)||0)),recent:Math.max(0,Math.min(1,Number.isFinite(v?.recent)?v.recent:.5))});
 const validMetric=v=>v&&['attempts','misses','aided','last','recent'].every(k=>Number.isFinite(v[k]))&&v.attempts>=0&&v.attempts<=10000&&v.misses>=0&&v.misses<=v.attempts&&v.aided>=0&&v.aided<=v.attempts&&v.last>=0&&v.last<=Date.now()+60000&&v.recent>=0&&v.recent<=1;
 function sanitize(raw){const out={enabled:raw?.enabled!==false,phrases:{},skills:{},seen:{}};for(const [id,v]of Object.entries(raw?.phrases||{}))if(all.has(id)&&validMetric(v))out.phrases[id]=cleanMetric(v);for(let day=1;day<=30;day++)for(const skill of skills){const key=day+':'+skill,v=raw?.skills?.[key];if(validMetric(v))out.skills[key]=cleanMetric(v)}for(const [id,at]of Object.entries(raw?.seen||{}))if(typeof id==='string'&&id.length<160&&Number.isFinite(at)&&at>0&&at<=Date.now()+60000)out.seen[id]=at;out.seen=Object.fromEntries(Object.entries(out.seen).sort((a,b)=>a[1]-b[1]).slice(-600));return out}
 state.adaptive=sanitize(state.adaptive);
 function observe({id,day,audio,skill,correct,aided=false,self=false}){if(!skills.includes(skill)||!Number.isInteger(day)||day<1||day>30||typeof correct!=='boolean'||typeof id!=='string')return;const s=state.adaptive,date=new Date(Date.now()).toISOString().slice(0,10),key=date+':'+id;if(s.seen[key])return;s.seen[key]=Date.now();s.seen=Object.fromEntries(Object.entries(s.seen).sort((a,b)=>a[1]-b[1]).slice(-600));const weight=self ? 0.5 : 1,value=correct&&!aided?1:aided ? 0.35 : 0;const update=(table,k)=>{const v=table[k]||cleanMetric();v.attempts+=weight;v.misses+=correct?0:weight;v.aided+=aided?weight:0;v.last=Date.now();v.recent=v.recent*.7+value*.3;table[k]=v};update(s.skills,day+':'+skill);if(all.has(audio))update(s.phrases,audio);save()}
 const need=v=>v?.attempts?(1-v.recent)*.65+(v.misses+v.aided*.65)/(v.attempts+2)*.35:0;
 function plan(day,due=[]){const current=data.expanded.lessons[day-1].examples.map(p=>({...p,day})),s=state.adaptive;if(!s.enabled)return {phrases:current.slice(0,3),focus:'balanced',reason:'Обычный круг из трёх фраз текущего урока.'};const weak=Object.entries(s.phrases).filter(([,v])=>(v.misses||v.aided)&&need(v)>=.35).sort((a,b)=>need(b[1])-need(a[1])||a[1].last-b[1].last).map(([id])=>all.get(id));const dueP=due.map(id=>all.get(id)).filter(Boolean),old=[...new Map([...dueP,...weak].map(p=>[p.audio,p])).values()].slice(0,2);const phrases=[...new Map([...old,...current].map(p=>[p.audio,p])).values()].slice(0,3);const dayScores=skills.map(skill=>({skill,v:s.skills[day+':'+skill]})).filter(x=>x.v&&(x.v.misses||x.v.aided)&&need(x.v)>=.38).sort((a,b)=>need(b.v)-need(a.v));const globalScores=skills.map(skill=>{const rows=Object.entries(s.skills).filter(([key])=>key.endsWith(':'+skill)).map(([,v])=>v),attempts=rows.reduce((n,v)=>n+v.attempts,0);return {skill,v:{attempts,misses:rows.reduce((n,v)=>n+v.misses,0),aided:rows.reduce((n,v)=>n+v.aided,0),recent:attempts?rows.reduce((n,v)=>n+v.recent*v.attempts,0)/attempts:1}}}).filter(x=>x.v.attempts>=2&&need(x.v)>=.38).sort((a,b)=>need(b.v)-need(a.v));const focus=dayScores[0]?.skill||globalScores[0]?.skill||'balanced';return {phrases,focus,reason:old.length?'В круг вошли фразы к повторению и фразы с ошибками или подсказками; одна новая модель текущего урока остаётся.':focus!=='balanced'?'Порядок заданий подстроен под ошибки в этой теме.':'Чередуем слух, воспоминание и ответ по ситуации.'}}
 function merge(raw){const incoming=sanitize(raw);for(const table of ['phrases','skills'])for(const [key,v]of Object.entries(incoming[table]))if(!state.adaptive[table][key]||state.adaptive[table][key].last<v.last)state.adaptive[table][key]=v;state.adaptive.seen=Object.fromEntries(Object.entries({...incoming.seen,...state.adaptive.seen}).sort((a,b)=>a[1]-b[1]).slice(-600))}
 return {observe,plan,sanitize,merge};
}};
