/* Lumo is a prepared, contextual study companion. It never grades speech or invents answers. */
window.VamosExperience={create(api){
 'use strict';
 const {state,data,esc,mascot,playButton}=api;
 let phraseIndex=0,phraseDay=0,mode='listen',lastRoute='',lastFeedback='',returnFocus=null,restoreFocus=true,pending=null;
 const animations=new Set();
 const context=()=>api.context?.()||{};
 const day=()=>{const c=context();return Math.min(30,Math.max(1,Number(c.contentDay)||(c.day===24?state.repairDay:state.recovery&&[22,23].includes(c.day)?c.day===22?19:20:c.day)||state.day||1))};
 const lesson=()=>data.expanded?.lessons?.[day()-1]||{};
 const phrases=()=>Array.isArray(lesson().examples)?lesson().examples.filter(p=>p.es&&p.ru&&p.audio):[];
 const reduced=()=>document.documentElement.classList.contains('motion-off')||matchMedia('(prefers-reduced-motion: reduce)').matches||document.hidden;
 const launcher=document.createElement('button');launcher.type='button';launcher.className='lumo-launcher';launcher.dataset.lumo='open';launcher.setAttribute('aria-label','Лумо: помощь с заданием и произношением');launcher.setAttribute('aria-haspopup','dialog');launcher.innerHTML=mascot('wave','lumo-mini')+'<span><strong>Лумо</strong><small>Я рядом</small></span>';
 const dialog=document.createElement('dialog');dialog.className='lumo-dialog';dialog.setAttribute('aria-labelledby','lumo-title');
 (document.querySelector('#app')||document.body).append(launcher,dialog);
 function animate(el,frames,options){if(!el||reduced()||!el.animate)return;const a=el.animate(frames,options);animations.add(a);a.finished.catch(()=>{}).finally(()=>animations.delete(a));}
 function cancelAnimations(){animations.forEach(a=>a.cancel());animations.clear();}
 function guide(){const c=context(),e=lesson();if(c.view==='lesson'&&c.stage===1)return 'Сначала включи запись в задании. Вспомни смысл, затем выбери ответ. Если не разобрал слова, послушай на ×0,5.';if(c.view==='lesson'&&c.stage===3)return 'Собери именно фразу из образца. Нажми на слово в ответе, чтобы вернуть его обратно. Объяснение покажет, почему слова стоят так.';if(c.view==='lesson'&&c.stage===5)return 'Вспомни фразу по русскому смыслу. Сначала попробуй сам; если застрял, открой подсказку в задании. Потом произнеси ответ вслух.';if(c.kind==='mission')return 'Сначала ответь партнёру без образца. Потом сравни реплику и попробуй заменить один факт на свой.';if(c.view==='words')return 'Слушай ту запись, текст которой показан рядом. После прослушивания закрой перевод и вспомни смысл. Верни трудное в повторение.';return e.mission||'Послушай короткую фразу, повтори её и попробуй сказать в своей ситуации.';}
 function body(){const e=lesson(),list=phrases(),p=list[phraseIndex%Math.max(1,list.length)],canExplain=!!document.querySelector('main .explain-panel');return `<header class="lumo-dialog-head">${mascot('think','lumo-host')}<div><h2 id="lumo-title">Давай разберёмся</h2><p>Лумо · твой напарник по испанскому</p></div><button type="button" class="lumo-close" data-lumo="close" aria-label="Закрыть помощь"><span aria-hidden="true">×</span></button></header><div class="lumo-tabs" role="group" aria-label="Помощь Лумо"><button type="button" data-lumo="listen" aria-pressed="${mode==='listen'}">Послушаем</button><button type="button" data-lumo="help" aria-pressed="${mode==='help'}">Разберём задание</button></div>${mode==='listen'?`<section class="lumo-native recorded-context"><h3>Скажи вслед за носителем</h3>${p?`<div class="lumo-phrase"><p lang="es">${esc(p.es)}</p><p>${esc(p.ru)}</p>${playButton(p.audio,'Слушать запись носителя: '+p.es,true)}</div><label class="lumo-speed">Темп записи<select class="select" data-audio-speed aria-label="Скорость записи у Лумо">${[.5,.75,.85,1,1.25].map(v=>`<option value="${v}" ${v===state.audioSpeed?'selected':''}>×${String(v).replace('.',',')}</option>`).join('')}</select></label><p class="lumo-instruction">Слушай → повтори → отведи взгляд и вспомни. В записи звучит ровно эта фраза.</p><div class="lumo-phrase-controls"><span>${phraseIndex%list.length+1} / ${list.length}</span><button type="button" data-lumo="next">Другая фраза <span aria-hidden="true">→</span></button></div>`:'<p>У этой темы пока нет записи. Прослушай доступный образец в уроке.</p>'}</section>`:`<section class="lumo-task-help"><h3>Попробуй так</h3><p>${esc(guide())}</p>${e.pattern?`<p class="lumo-pattern" lang="es">${esc(e.pattern)}</p>`:''}${e.explanation?`<details><summary>Почему фраза устроена так?</summary><p>${esc(e.explanation)}</p></details>`:''}${canExplain?'<button type="button" class="btn" data-lumo="explain">Открыть пояснения в задании</button>':''}</section>`}<div class="lumo-actions"><button type="button" class="btn primary" data-lumo="study">${context().view==='lesson'?'Вернуться к уроку':'Продолжить обучение'}</button><button type="button" class="btn quiet" data-lumo="mission">Разыграть разговор дня</button></div>`}
 function paint(){if(dialog.querySelector('.playing[aria-pressed="true"]'))api.stopAudio?.();const focused=document.activeElement,action=dialog.contains(focused)?focused.dataset.lumo:null;dialog.innerHTML=body();window.lucide?.createIcons?.();if(action)dialog.querySelector(`[data-lumo="${action}"]`)?.focus({preventScroll:true});}
 function close(restore=true){restoreFocus=restore;if(dialog.open)dialog.close();}
 function open(){restoreFocus=true;returnFocus=document.activeElement;paint();dialog.showModal();dialog.querySelector('[data-lumo="close"]')?.focus();animate(dialog,[{transform:'translateY(18px) scale(.97)',clipPath:'inset(5% 0 0 round 28px)'},{transform:'none',clipPath:'inset(0 round 28px)'}],{duration:300,easing:'cubic-bezier(.16,1,.3,1)'});}
 dialog.addEventListener('close',()=>{if(dialog.querySelector('.playing[aria-pressed="true"]'))api.stopAudio?.();if(!restoreFocus)return;if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else launcher.focus({preventScroll:true});});
 dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();});
 dialog.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const controls=[...dialog.querySelectorAll('button:not([disabled]),summary,a[href],input,textarea,select')].filter(el=>el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}});
 function click(button){const action=button.dataset.lumo;const playing=!!document.querySelector('.playing[aria-pressed="true"]');if(!action){if(!playing&&(button.hasAttribute('data-nav')||button.hasAttribute('data-footer-nav')||button.hasAttribute('data-practice-open')))api.sound?.('tap');return false}if(!playing)api.sound?.('tap');if(action==='open')open();else if(action==='close')close();else if(action==='listen'||action==='help'){mode=action;paint()}else if(action==='next'){phraseIndex=(phraseIndex+1)%Math.max(1,phrases().length);paint();animate(dialog.querySelector('.lumo-phrase'),[{transform:'translateX(8px)',opacity:.65},{transform:'none',opacity:1}],{duration:240,easing:'ease-out'})}else if(action==='explain'){close(false);const panel=document.querySelector('main .explain-panel');if(panel){panel.open=true;panel.querySelector('summary')?.focus({preventScroll:true});panel.scrollIntoView({block:'center',behavior:reduced()?'auto':'smooth'});}}else if(action==='study'){close(context().view==='lesson');if(context().view!=='lesson')api.startStudy?.()}else if(action==='mission'){const current=context();close(false);api.openPractice?.('mission',Number(current.day)||state.day||1)}return true}
 function mood(){const feedback=document.querySelector('main .feedback'),complete=!!document.querySelector('main .guided-finish,main .session-complete'),playing=!!document.querySelector('.playing[aria-pressed="true"],.is-playing');const pose=playing?'listen':complete?'joy':feedback?feedback.classList.contains('wrong')?'think':'proud':'wave';launcher.dataset.mood=pose;const image=launcher.querySelector('.mascot');if(image)image.dataset.pose=pose==='listen'?'think':pose;const label=launcher.querySelector('small'),text=playing?'Слушаем':complete?'Получилось!':feedback?feedback.classList.contains('wrong')?'Давай разберём':'Отличный шаг':'Я рядом';if(label.textContent!==text)label.textContent=text;const signature=feedback?context().day+':'+context().stage+':'+feedback.className+':'+feedback.textContent.slice(0,80):complete?'complete:'+context().day:'';if(signature&&signature!==lastFeedback){lastFeedback=signature;launcher.classList.remove('lumo-celebrate');if(pose==='proud'||pose==='joy'){launcher.classList.add('lumo-celebrate');animate(image,[{transform:'rotate(0deg)'},{transform:'translateY(-7px) rotate(-8deg)',offset:.4},{transform:'rotate(3deg)',offset:.75},{transform:'none'}],{duration:520,easing:'ease-out'})}}if(!signature)lastFeedback='';}
 function sync(){const content=day();if(content!==phraseDay){phraseDay=content;phraseIndex=0;if(dialog.open)paint()}const c=context();launcher.classList.toggle('lumo-in-lesson',c.view==='lesson');mood();transition();}
 function transition(){const c=context(),key=[c.view,c.kind,c.day,c.view==='lesson'?c.stage:''].join(':');if(lastRoute&&lastRoute!==key){const main=document.querySelector('main');animate(main,[{transform:'translateY(10px)',opacity:.8,clipPath:'inset(0 0 3px)'},{transform:'none',opacity:1,clipPath:'inset(0)'}],{duration:280,easing:'cubic-bezier(.16,1,.3,1)'});}lastRoute=key;}
 const main=document.querySelector('main');if(main)new MutationObserver(()=>{if(pending)return;pending=requestAnimationFrame(()=>{pending=null;mood()})}).observe(main,{subtree:true,childList:true,attributes:true,attributeFilter:['class','aria-pressed']});
 new MutationObserver(()=>{if(pending)return;pending=requestAnimationFrame(()=>{pending=null;mood()})}).observe(dialog,{subtree:true,childList:true,attributes:true,attributeFilter:['class','aria-pressed']});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimations()});
 matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(reduced())cancelAnimations()});
 return {sync,click,close,transition};
}};
