/* Device features are optional; the current page is the only reminder scheduler. */
window.VamosIdentity={create(api){
 'use strict';
 const {state,esc,save,toast,dueKeys}=api;
 const poses=['wave','joy','think','proud'],labels={wave:'Приветствие',joy:'Радость',think:'Размышление',proud:'Поддержка'};
 const prior=state.identity||{};
 state.identity={installPose:poses.includes(prior.installPose)?prior.installPose:'wave',badge:prior.badge===true,reminder:prior.reminder===true,time:/^([01]\d|2[0-3]):[0-5]\d$/.test(prior.time||'')?prior.time:'18:00',lastDate:/^\d{4}-\d{2}-\d{2}$/.test(prior.lastDate||'')?prior.lastDate:''};
 const prefs=()=>state.identity;
 const installed=()=>window.matchMedia?.('(display-mode: standalone)').matches===true||navigator.standalone===true;
 const canNotify=()=>window.isSecureContext===true&&typeof window.Notification?.requestPermission==='function';
 const canBadge=()=>window.isSecureContext===true&&typeof navigator.setAppBadge==='function'&&typeof navigator.clearAppBadge==='function';
 const count=()=>{try{return Math.max(0,Array.from(dueKeys?.()||[]).length)}catch{return 0}};
 let permissionPending=false,reminderPending=false,lastBadge=null,badgePending=false,badgeFailed=false,note='',lastPose='';
 const timeZone=()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'}catch{return 'UTC'}};
 const icsEscape=s=>String(s).replace(/\\/g,'\\\\').replace(/\r\n|\r|\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
 function foldICS(line){const encoder=new TextEncoder();let folded='',row='',bytes=0;for(const c of line){const n=encoder.encode(c).length;if(bytes+n>75){folded+=row+'\r\n';row=' ';bytes=1}row+=c;bytes+=n}return folded+row;}
 const localStamp=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('')+'T'+[d.getHours(),d.getMinutes(),d.getSeconds()].map(n=>String(n).padStart(2,'0')).join('');
 function calendarFile(now=new Date()){
  const start=new Date(now.getTime()),[hour,minute]=prefs().time.split(':').map(Number);start.setHours(hour,minute,0,0);if(start<=now)start.setDate(start.getDate()+1);
  const end=new Date(start.getTime()+15*60000),stamp=now.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');
  const url=new URL('./?view=home',location.href).href;
  // DTSTART/DTEND intentionally float in the importing calendar's local time.
  const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Vamos Spanish//Local study reminder//RU','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:'+icsEscape('¡Vamos! · испанский'),'X-WR-TIMEZONE:'+icsEscape(timeZone()),'BEGIN:VEVENT','UID:vamos-local-study@vamos-spanish','DTSTAMP:'+stamp,'DTSTART:'+localStamp(start),'DTEND:'+localStamp(end),'RRULE:FREQ=DAILY','SUMMARY:'+icsEscape('15 минут испанского с Лумо'),'DESCRIPTION:'+icsEscape('Открой ¡Vamos!: вспомни несколько фраз и скажи свой ответ. Это короткое повторение, а не полное дневное занятие. Напоминание работает после импорта в календарь устройства; расписание можно изменить или удалить там.\n'+url),'URL:'+icsEscape(url),'BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY','DESCRIPTION:'+icsEscape('Пора вспомнить испанский с Лумо'),'END:VALARM','END:VEVENT','END:VCALENDAR'];
  return lines.map(foldICS).join('\r\n')+'\r\n';
 }
 function downloadCalendar(){try{const file=new Blob([calendarFile()],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download='vamos-daily-study.ics';document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000);note='Файл календаря готов. Открой его и подтверди импорт ежедневного события на устройстве.';toast(note)}catch{note='Не удалось создать файл календаря. Попробуй в основном браузере устройства.';toast(note)}paint();}
 function pose(){const c=api.context?.()||{};if((c.view==='lesson'&&c.stage===7)||((c.view==='lesson'||c.view==='practice')&&c.result?.correct===true))return 'joy';if(c.view==='lesson'||c.kind==='mission'||count()>0)return 'think';if((state.completed||[]).length>=5)return 'proud';return 'wave'}
 function network(){return navigator.onLine===false?'Без сети · доступны сохранённые материалы':'Соединение с сетью есть · доступность сервера зависит от сети'}
 function notificationStatus(){if(!canNotify())return 'Этот браузер не поддерживает уведомления здесь. Напоминание можно поставить в календаре устройства.';if(window.Notification.permission==='denied')return 'Уведомления запрещены в браузере. Измени разрешение в настройках сайта, если захочешь их включить.';if(prefs().reminder&&window.Notification.permission==='granted')return 'Включено: проверяем местное время, пока приложение открыто и видно на экране.';return 'Уведомления выключены. Разрешение запрашивается только по кнопке.'}
 function badgeStatus(){if(!canBadge())return 'Счётчик на значке недоступен в этом браузере.';if(!installed())return 'Счётчик работает в установленном приложении, если его поддерживает система.';if(badgeFailed)return 'Система не разрешила обновить счётчик. Количество карточек видно в приложении.';return prefs().badge?'На значке — карточки, срок повторения которых наступил. Это не оценка знания.':'Счётчик выключен.'}
 function html(){return `<section class="identity-settings" aria-labelledby="identity-title"><div class="identity-heading"><img src="assets/favicon-lumo-${pose()}.png" width="64" height="64" alt="Лумо"><div><h2 id="identity-title">Лумо на твоём устройстве</h2><p>Выбери удобное время для короткого повторения.</p></div></div><h3>15 минут испанского каждый день</h3><label for="identity-time">Местное время устройства<input id="identity-time" type="time" value="${esc(prefs().time)}"></label><p class="small">Часовой пояс: ${esc(timeZone())}. Событие календаря использует местное время устройства.</p><button type="button" class="btn primary" data-identity-calendar>Добавить в календарь</button><p class="small">Скачается файл .ics. Открой его и подтверди импорт: календарь сможет напоминать и при закрытом сайте. Расписание и разрешение уведомлений меняются в календаре устройства.</p><details><summary>Уведомления открытого приложения</summary><div><div class="identity-notification-actions"><button type="button" class="btn" data-identity-reminder ${!canNotify()||window.Notification?.permission==='denied'||permissionPending?'disabled':''}>${prefs().reminder?'Выключить напоминание':'Включить напоминание'}</button></div><p data-identity-notification-status class="small" role="status">${esc(notificationStatus())}</p><p class="identity-limit">Эти уведомления проверяют время, пока приложение открыто и видно. При закрытом или свёрнутом сайте доставки нет.</p></div></details><details><summary>Значок Лумо и счётчик повторения</summary><div><div class="identity-poses" role="group" aria-label="Выбрать Лумо для значка">${poses.map(p=>`<button type="button" class="identity-pose" data-identity-pose="${p}" aria-pressed="${prefs().installPose===p}"><img src="assets/app-icon-lumo-${p}-192.png" alt="" width="56" height="56"><span>${labels[p]}</span></button>`).join('')}</div><p class="small">Вкладка меняет выражение Лумо по текущему занятию. Для будущей установки выбран ${esc(labels[prefs().installPose].toLowerCase())}. Значок уже установленного приложения сайт автоматически не заменяет.</p><label class="setting-check"><input type="checkbox" id="identity-badge" ${prefs().badge?'checked':''} ${!canBadge()?'disabled':''}>Показывать число карточек к повторению на значке</label><p data-identity-badge-status class="small" role="status">${esc(badgeStatus())}</p></div></details><p class="identity-limit">Системные виджеты эта веб-версия не создаёт. Слова для короткого повторения доступны на главной странице.</p><p class="identity-network" data-identity-network role="status">${esc(network())}</p><p data-identity-note class="small" role="status">${esc(note)}</p></section>`}

 function setText(selector,text){document.querySelectorAll(selector).forEach(el=>{el.textContent=text})}
 function paint(){setText('[data-identity-network]',network());setText('[data-identity-badge-status]',badgeStatus());setText('[data-identity-notification-status]',notificationStatus());setText('[data-identity-note]',note);document.querySelectorAll('[data-identity-reminder]').forEach(el=>{el.disabled=!canNotify()||window.Notification?.permission==='denied'||permissionPending;el.textContent=permissionPending?'Ожидаем решение браузера…':prefs().reminder?'Выключить напоминание':'Включить напоминание'})}
 function favicon(){const p=pose();if(lastPose===p)return;let link=document.querySelector('link[rel="icon"]');if(!link){link=document.createElement('link');link.rel='icon';document.head.appendChild(link)}link.type='image/png';link.href=new URL(`assets/favicon-lumo-${p}.png`,location.href).href;lastPose=p}
 function installIcon(){const link=document.querySelector('link[rel="manifest"]');if(link)link.href=new URL(`manifest-lumo-${prefs().installPose}.webmanifest`,location.href).href}
 async function badge(){if(badgePending||document.hidden)return;const n=prefs().badge?count():0,key=String(prefs().badge)+':'+n;if(lastBadge===key||!canBadge()||!installed())return;badgePending=true;try{if(n>0)await navigator.setAppBadge(n);else await navigator.clearAppBadge();lastBadge=key;badgeFailed=false}catch{lastBadge=key;badgeFailed=true}finally{badgePending=false;paint()}}
 async function reminder(){if(reminderPending||document.hidden||!prefs().reminder||!canNotify()||window.Notification.permission!=='granted')return;const now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-'),minutes=now.getHours()*60+now.getMinutes(),target=prefs().time.split(':').map(Number);if(minutes<target[0]*60+target[1]||prefs().lastDate===today)return;reminderPending=true;prefs().lastDate=today;save();const n=count(),body=n?`К повторению: ${n} карточек. Открой ¡Vamos! и вспомни несколько фраз.`:'Есть пара минут? Открой ¡Vamos! и повтори знакомую фразу.';try{let registration=null;if(typeof navigator.serviceWorker?.getRegistration==='function')registration=await navigator.serviceWorker.getRegistration();if(document.hidden){prefs().lastDate='';save();return}if(typeof registration?.showNotification==='function')await registration.showNotification('Лумо · немного испанского',{body,icon:'assets/app-icon-lumo-192.png',badge:'assets/favicon-lumo-wave.png',tag:'vamos-local-review',data:{url:'./?view=home'}});else{const notification=new window.Notification('Лумо · немного испанского',{body,icon:'assets/app-icon-lumo-192.png',tag:'vamos-local-review'});notification.onclick=()=>{window.focus?.();notification.close?.()}}note='Сегодняшнее напоминание отправлено браузеру.'}catch{note='Браузер не смог показать уведомление. Можно повторить слова на главной странице.';toast(note)}finally{reminderPending=false;paint()}}
 async function toggleReminder(){if(permissionPending)return;if(prefs().reminder){prefs().reminder=false;save();paint();return}if(!canNotify()||window.Notification.permission==='denied'){note=notificationStatus();paint();return}permissionPending=true;paint();try{const result=window.Notification.permission==='granted'?'granted':await window.Notification.requestPermission();prefs().reminder=result==='granted';save();if(result!=='granted')note=result==='denied'?'Разрешение не получено. Напоминание выключено.':'Запрос закрыт. Напоминание выключено.'}catch{prefs().reminder=false;save();note='Не удалось запросить разрешение. Напоминание выключено.'}finally{permissionPending=false;paint();if(prefs().reminder)await reminder()}}
 function sync(){favicon();paint();return Promise.allSettled([badge(),reminder()])}
 function click(el){const p=el.getAttribute?.('data-identity-pose');if(poses.includes(p)){prefs().installPose=p;save();installIcon();note='Выбран значок для будущей установки. Система может кешировать прежний значок.';api.render?.();return true}if(el.hasAttribute('data-identity-calendar')){downloadCalendar();return true}if(el.hasAttribute('data-identity-reminder')){toggleReminder();return true}return false}
 function change(el){if(el.id==='identity-badge'){prefs().badge=el.checked===true;lastBadge=null;save();sync();return true}if(el.id==='identity-time'){if(/^([01]\d|2[0-3]):[0-5]\d$/.test(el.value)){prefs().time=el.value;save();sync()}return true}return false}
 installIcon();window.addEventListener('online',paint);window.addEventListener('offline',paint);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});window.setInterval(()=>{if(!document.hidden)sync()},60000);
 return {html,sync,click,change,calendarFile};
}};
