/* Progressive enhancement: installation, explicit offline audio and screen wake lock. */
window.VamosNative={create(api){
 'use strict';
 const {state,data,esc,icon,save,toast,activeLesson}=api;
 state.native={awake:state.native?.awake===true};
 const scope=new URL('./',location.href),prefix='vamos-'+encodeURIComponent(scope.pathname)+'-',mediaCache=prefix+'audio';
 let ready=false,lockPending=false,registration=null,prompt=null,status='Проверяем поддержку офлайн-режима…',busy=false,downloaded=0,cancel=null,lock=null,installed=matchMedia('(display-mode: standalone)').matches;
 const clips=Object.values(data.expanded.audio);
 const supported='serviceWorker'in navigator&&'caches'in window;
 function update(){const el=document.getElementById('offline-status');if(el)el.textContent=status;document.querySelectorAll('[data-offline-download]').forEach(b=>{b.disabled=busy||!supported||!ready;b.setAttribute('aria-busy',String(busy))});const install=document.querySelector('[data-native-install]');if(install)install.textContent=installed?'Уже открыто как приложение':prompt?'Установить ¡Vamos!':'Как добавить на главный экран';const cancelButton=document.querySelector('[data-offline-cancel]');if(cancelButton)cancelButton.hidden=!busy}
 async function count(){if(!supported)return 0;const cache=await caches.open(mediaCache),matches=await Promise.all(clips.map(p=>cache.match(new URL(p.file,scope).href)));return matches.filter(Boolean).length}
 async function refresh(){try{downloaded=await count();status=supported?`На устройстве: ${downloaded} из ${clips.length} записей носителя. ${downloaded===clips.length?'Все записи доступны офлайн.':'Для офлайн-аудио сохрани курс кнопкой ниже.'}`:'Офлайн-хранилище не поддерживается. Курс доступен с интернетом.'}catch{status='Браузер не разрешил доступ к офлайн-хранилищу.'}update()}
 function html(){return `<section class="native-settings"><h2>Курс под рукой</h2><p>Добавь ¡Vamos! на главный экран. В поддерживаемых системах у значка появятся быстрые действия: маршрут, повторение и речь. Это зависит от браузера.</p><button type="button" class="btn" data-native-install ${installed?'disabled':''}>${installed?'Уже открыто как приложение':prompt?'Установить ¡Vamos!':'Как добавить на главный экран'}</button><details id="install-help"><summary>Инструкция для телефона</summary><div><p>iPhone/iPad: открой сайт в Safari → «Поделиться» → «На экран Домой».</p><p>Android: открой меню браузера → «Установить приложение» или «Добавить на главный экран». Если кнопки нет, продолжай учиться во вкладке.</p><p>Прогресс привязан к хранилищу браузера. Перед сменой браузера сохрани файл прогресса ниже.</p></div></details><h3>Оригинальные записи без интернета</h3><p class="note">Сохранение загрузит ${clips.length} оригинальных MP3. Произношение через сервис браузера требует сети; запись себя и сохранённые уроки работают отдельно. Браузер может очистить кэш при нехватке места.</p><div class="transfer-actions"><button type="button" class="btn primary" data-offline-download ${busy||!supported||!ready?'disabled':''} aria-busy="${busy}">${icon('download')}${busy?'Сохраняем записи…':'Сохранить аудио офлайн'}</button><button type="button" class="btn" data-offline-cancel ${!busy?'hidden':''}>Остановить загрузку</button><button type="button" class="btn quiet" data-offline-refresh>${icon('refresh-cw')}Проверить</button></div><p id="offline-status" role="status">${esc(status)}</p><label class="setting-check"><input type="checkbox" id="native-awake" ${state.native.awake?'checked':''} ${!navigator.wakeLock?'disabled':''}>Не гасить экран во время урока</label><p class="small">${navigator.wakeLock?'Браузер может снять блокировку при экономии батареи. При уходе из урока экран работает как обычно.':'Этот браузер не поддерживает удержание экрана. Измени время автоблокировки в настройках устройства, если нужно.'}</p></section>`}
 async function download(){if(busy||!supported||!ready){toast('Офлайн-хранилище ещё не готово. Проверь статус ниже.');return;}busy=true;cancel=new AbortController();const signal=cancel.signal;status='Подготавливаем хранилище…';update();let success=0,failed=0,next=0;try{await navigator.serviceWorker.ready;const cache=await caches.open(mediaCache);await Promise.all(Array.from({length:3},async()=>{while(next<clips.length&&!signal.aborted){const item=clips[next++],url=new URL(item.file,scope).href;try{if(!await cache.match(url)){const response=await fetch(url,{signal});if(!response.ok||response.status!==200)throw Error('http');await cache.put(url,response)}success++}catch{if(!signal.aborted)failed++}status=`Сохранено ${success} из ${clips.length}${failed?`; не удалось: ${failed}`:''}.`;update()}}));}catch{status='Не удалось сохранить аудио. Проверь соединение и свободное место.'}finally{busy=false;cancel=null;await refresh();if(failed)status+=` Не удалось загрузить: ${failed}. Повтори сохранение — готовые файлы останутся.`;if(signal.aborted)status+=' Загрузка остановлена.';update()}}
 function notice(){if(!registration?.waiting||!navigator.serviceWorker.controller)return;let el=document.getElementById('native-notice');if(!el){el=document.createElement('div');el.id='native-notice';el.className='native-notice';el.setAttribute('role','status');document.querySelector('.layout').before(el)}el.innerHTML='<span>Доступно обновление курса. Сохранённый шаг останется.</span><button type="button" class="btn" data-native-update>Обновить</button>'}
 async function sync(){if(!navigator.wakeLock)return;const want=state.native.awake&&activeLesson()&&!document.hidden;if(!want){if(lock){const current=lock;lock=null;await current.release().catch(()=>{})}return}if(lock||lockPending)return;lockPending=true;try{const result=await navigator.wakeLock.request('screen');if(!state.native.awake||!activeLesson()||document.hidden){await result.release();return}lock=result;result.addEventListener('release',()=>{if(lock===result)lock=null})}catch{}finally{lockPending=false}}
 function click(b){if(b.hasAttribute('data-native-install')){if(prompt){const current=prompt;prompt=null;current.prompt().then(()=>current.userChoice).then(r=>{if(r.outcome==='accepted')toast('Подтверди установку в интерфейсе браузера.');update()}).catch(()=>toast('Открой инструкцию установки ниже.'))}else{const el=document.getElementById('install-help');el.open=true;el.scrollIntoView({block:'center'})}return true}if(b.hasAttribute('data-offline-download')){download();return true}if(b.hasAttribute('data-offline-cancel')){cancel?.abort();return true}if(b.hasAttribute('data-offline-refresh')){refresh();return true}if(b.hasAttribute('data-native-update')){save();registration?.waiting?.postMessage({type:'ACTIVATE'});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});return true}return false}
 function change(el){if(el.id==='native-awake'){state.native.awake=el.checked;save();sync();return true}return false}
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;update()});window.addEventListener('appinstalled',()=>{installed=true;prompt=null;update()});document.addEventListener('visibilitychange',sync);window.addEventListener('pagehide',()=>lock?.release().catch(()=>{}));
 if(supported){navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>{registration=r;ready=!!r.active;notice();navigator.serviceWorker.ready.then(()=>{ready=true;refresh()});r.addEventListener('updatefound',()=>r.installing?.addEventListener('statechange',notice));refresh()}).catch(()=>{status='Офлайн-режим пока не включился. Курс работает с интернетом.';update()})}else refresh();
 return {html,click,change,sync};
}};
