/* A local learner profile. Activity, self-report and delayed evidence stay separate. */
window.VamosProfile={create(api){
 'use strict';
 const {state,data,esc,icon=()=>'',mascot=()=>'',save=()=>{},render=()=>{},toast=()=>{},footer=()=>'',openPractice=()=>{},openLesson=()=>{},settingsHTML=()=>''}=api;
 const DAY=86400000,validDay=n=>Number.isInteger(n)&&n>=1&&n<=30,stamp=n=>Number.isFinite(n)&&n>0&&n<=Date.now()+60000;
 const list=v=>Array.isArray(v)?v:[],clean=(v,max=60)=>typeof v==='string'?v.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max):'';
 function sanitize(raw){return {nickname:clean(raw?.nickname,40),goal:['conversation','travel','habit'].includes(raw?.goal)?raw.goal:'conversation',pace:[30,60,90].includes(raw?.pace)?raw.pace:30,showWeek:raw?.showWeek!==false,showPractice:raw?.showPractice!==false,showLumo:raw?.showLumo!==false}}
 state.profile=sanitize(state.profile);
 const p=()=>state.profile,dateKey=t=>{const d=new Date(t);return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`};
 function next(){const n=api.nextDay?.();return validDay(n)?n:list(data.lessons).find(l=>!list(state.completed).includes(l.day))?.day||30}
 function evidence(){
  const completed=[...new Set(list(state.completed).filter(validDay))],events=[...new Map(list(state.learning?.events).filter(e=>e&&typeof e.id==='string'&&e.id.length<140&&['answer','review','speech','lesson','drill','mastery'].includes(e.kind)&&validDay(e.day)&&stamp(e.time)).map(e=>[e.id,e])).values()];
  const week=Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-6+i);return {label:d.toLocaleDateString('ru',{weekday:'short'}),count:events.filter(e=>dateKey(e.time)===dateKey(d.getTime())).length}});
  const retained=[],initial=[];
  for(let day=1;day<=30;day++){const v=state.mastery?.[day];if(!v)continue;const h=list(v.history).filter(x=>{if(!x||!stamp(x.at)||x.correct!==3||x.aided!==false||!validDay(x.contentDay))return false;const e=data.expanded?.lessons?.[x.contentDay-1],idx=window.VAMOS_DRILLS?.[x.contentDay-1]?.index;if(!e||!Number.isInteger(idx))return false;const pool=list(e.examples).filter((_,i)=>i!==idx);return pool.length>=2&&x.modelSet===[pool[0].audio,pool[1].audio,e.examples[idx]?.audio].join(':')});const first=h.find(x=>x.at===v.firstAt);if(!first)continue;initial.push(day);if(h.some(x=>x.at===v.retainedAt&&x.contentDay===first.contentDay&&x.modelSet===first.modelSet&&x.at-first.at>=DAY))retained.push(day)}
  const variants=new Map(list(data.missions?.days).flatMap(d=>list(d.variants).map(v=>[v.id,{...v,day:d.day}])));
  const missions=[...new Map(list(state.missions?.history).filter(m=>{const v=variants.get(m?.variant);return v&&validDay(m.day)&&v.day===m.day&&typeof m.id==='string'&&/^m-\d+-[a-z0-9-]+$/.test(m.id)&&stamp(m.startedAt)&&stamp(m.completedAt)&&m.completedAt>=m.startedAt&&list(m.responses).length===list(v.turns).length&&m.responses.every(r=>r?.first&&stamp(r.first.at)&&r.first.at>=m.startedAt&&r.first.at<=m.completedAt&&clean(r.first.text,500)&&['independent','hesitant','help','typed'].includes(r.first.oral))}).map(m=>[m.id,m])).values()];
  let firstResponses=0,independentSpeech=0;for(const m of missions)for(const r of m.responses){firstResponses++;if(r.first.oral==='independent')independentSpeech++}
  let stories=0,workshops=0,firstCorrect=0,firstTotal=0;
  for(let day=1;day<=30;day++)for(const section of ['story','workshop']){const tasks=section==='story'?data.stories?.days?.find(s=>s.day===day)?.questions:data.workshops?.days?.find(s=>s.day===day)?.tasks;if(!list(tasks).length)continue;const answers=list(tasks).map(t=>state.workbook?.days?.[day]?.answers?.[`${day}:${section}:${t.id}`]);for(const a of answers){if(stamp(a?.first?.time)&&typeof a.first.correct==='boolean'){firstTotal++;if(a.first.correct&&!a.first.aided)firstCorrect++}}if(answers.every(a=>{const f=a?.first;if(!stamp(f?.time)||typeof f.correct!=='boolean')return false;const last=list(a.retries).filter(r=>stamp(r?.time)&&r.time>=f.time&&typeof r.correct==='boolean').at(-1)||f;return last.correct===true})){if(section==='story')stories++;else workshops++}}
  return {completed,events,week,retained,initial,missions,firstResponses,independentSpeech,stories,workshops,firstCorrect,firstTotal};
 }
 function assistance(text){return p().showLumo?`<aside class="profile-lumo">${mascot('think')}<div><p>${esc(text)}</p><button type="button" class="btn quiet" data-lumo="open">${icon('messages-square')}Обсудить с Лумо</button></div></aside>`:''}
 const action=(kind,day,title,detail)=>`<button type="button" class="profile-daily-action" data-profile-action="${kind}" data-profile-day="${day}"><span><strong>${title}</strong><small>${esc(detail)}</small></span>${icon('arrow-right')}</button>`;
 function homeWidget(){const day=next(),l=data.lessons?.find(l=>l.day===day),story=data.stories?.days?.find(s=>s.day===day);if(!l)return '';const sourceId=({2:'greetings',4:'countries',5:'jobs',6:'intro',7:'intro',8:'likes',10:'likes',12:'clock',13:'weekend',26:'people',29:'greetings'})[day]||(day<=3?'greetings':day<=7?'intro':day<=11?'likes':day<=17?'weekend':day<=25?'intro':'people'),video=list(data.videoGuide?.items).find(v=>v.language==='ru-es'&&list(v.suggestedCoreDays).includes(day)&&/^https:\/\/tuespanol\.ru\//.test(v.url))||list(data.sources).find(s=>s.id===sourceId&&/^https:\/\/(www\.)?(youtube\.com|videoele\.com|profedeele\.es)\//.test(s.url));return `<section class="profile-daily" aria-labelledby="profile-daily-title"><div class="profile-section-head"><div><h2 id="profile-daily-title">Сегодня в испанском</h2><p>День ${day} · ${esc(l.title)}</p></div><button type="button" class="btn quiet" data-profile-action="profile">Мой профиль ${icon('user-round')}</button></div><p class="profile-daily-goal">${esc(l.goal)}</p><div class="profile-daily-list">${action('words',day,'Слова и фразы', 'Лексика этой темы · послушать в живом контексте')}${action('mission',day,'Ответить собеседнику',l.practice?.own||l.scene)}${action('pronunciation',day,'Произношение и свой голос','Скажи фразу дня и сравни с записью носителя')}${action('workbook',day,'Прочитать историю',story?.title||'История и свои фразы по теме')}</div>${video?`<details class="profile-video"><summary>Видео на сегодня · ${video.language==='ru-es'?'для русскоговорящих':'испанский, дополнительно'}</summary><div><a href="${esc(video.url)}" target="_blank" rel="noopener noreferrer">${esc(video.title)} ${icon('external-link')}</a><p><strong>Перед просмотром:</strong> ${esc(video.before)}</p><p><strong>После:</strong> ${esc(video.after)}</p><p class="small">${esc(video.languageLabel||"Испанский · дополнительный материал")}. Повтор знакомого материала допустим. ${esc(video.status)}</p></div></details>`:''}${p().showPractice?`<div class="profile-repeat"><div><h3>Вернуться к словам в течение дня</h3><p>Вспомни по смыслу, послушай ответ и честно отметь, нужна ли опора. Карточки используют общее расписание курса.</p></div><button type="button" class="btn" data-profile-action="review">Короткое повторение ${icon('rotate-ccw')}</button></div>`:''}${assistance('Не получается начать ответ? Открой разговор по теме, затем попроси меня разобрать одну реплику.')}</section>`}
 function pathwayProgress(){const raw=api.pathwaySummary?.(),days=list(data.pathway?.days),readings=list(data.pathway?.readings),completedDays=[...new Set(list(raw?.completedDays).filter(n=>Number.isInteger(n)&&n>=31&&n<=90&&days.some(d=>d.day===n)))],completedReadings=[...new Set(list(raw?.completedReadings).filter(id=>typeof id==='string'&&readings.some(r=>r.id===id)))];return {completedDays,completedReadings,totalDays:days.filter(d=>Number.isInteger(d.day)&&d.day>=31&&d.day<=90).length,totalReadings:readings.length}}
 function html(){
  const continuation=api.continuation?.(),extension=pathwayProgress(),e=evidence(),active=e.week.filter(d=>d.count>0).length,nextDay=next(),due=e.initial.find(d=>!e.retained.includes(d)&&Date.now()-state.mastery[d].firstAt>=DAY),lesson=data.lessons?.find(l=>l.day===nextDay),currentDay=continuation?.day||nextDay;
  const achievement=(done,title,detail)=>done?`<li class="achieved">${icon('check')}<div><strong>${title}</strong><p>${detail}</p></div></li>`:'';
  const hasAchievements=e.completed.length||e.missions.length||e.stories||e.workshops||e.retained.length;
  const achievementSummary=e.completed.length===30?'Основной курс пройден':e.retained.length?`Память через сутки: ${e.retained.length} наборов`:e.missions.length?`Завершённые разговорные попытки: ${e.missions.length}`:e.stories?`Разобранные истории: ${e.stories}`:e.workshops?`Выполненные мастерские: ${e.workshops}`:e.completed.length?'Первый урок завершён':'Пока нет записей';
  return `<section class="page profile-page">
   <header class="profile-heading"><h1>${p().nickname?esc(p().nickname)+' · мой испанский':'Мой испанский'}</h1><p>Завершено уроков: ${e.completed.length} из 30${extension.completedDays.length?` · Продолжение: ${extension.completedDays.length} из ${extension.totalDays}`:''}</p></header>
   <details class="page-fold profile-settings" data-fold="profile:settings"><summary>Настройки и резервная копия</summary><div>${settingsHTML()}</div></details>
   <section class="profile-next"><div><h2>День ${currentDay}</h2><p>${esc(continuation?.title||lesson?.title||'Продолжить испанский')}</p></div><button type="button" class="btn primary" data-profile-action="${continuation?'pathway':'lesson'}" data-profile-day="${currentDay}">Продолжить занятие ${icon('arrow-right')}</button></section>
   <details class="page-fold profile-evidence" data-fold="profile:evidence"><summary>Достижения · ${esc(achievementSummary)}</summary><div><ul>${!hasAchievements?'<li><div><strong>Первое достижение впереди</strong><p>Заверши урок или разговорную попытку — здесь появится запись.</p></div></li>':''}${achievement(e.completed.length>0,'Первый урок завершён',`${e.completed.length} уроков выполнено.`)}${achievement(e.missions.length>0,'Разговор доведён до конца',`${e.missions.length} разговорных попыток; ${e.firstResponses} первых ответов. Самостоятельная речь отмечена тобой в ${e.independentSpeech} ответах, без автоматической оценки звучания.`)}${achievement(e.stories>0||e.workshops>0,e.stories?'История разобрана':'Мастерская выполнена',`${e.stories} историй и ${e.workshops} мастерских с выполненными подготовленными заданиями. Без опоры верны ${e.firstCorrect} из ${e.firstTotal} первых ответов.`)}${achievement(e.retained.length>0,'Фразы вспомнились спустя сутки',`${e.retained.length} наборов с двумя успешными проверками без подсказки и паузой минимум 24 часа.`)}${achievement(e.completed.length===30,'Основной курс пройден','30 уроков завершено. Это завершение программы, а не сертификат владения языком.')}</ul></div></details>
   <details class="page-fold profile-identity" data-fold="profile:identity"><summary>Имя, цель и план занятий</summary><div><div class="profile-fields"><label for="profile-nickname">Имя в интерфейсе<input class="field" id="profile-nickname" type="text" maxlength="40" value="${esc(p().nickname)}" autocomplete="nickname" placeholder="Как к тебе обращаться"></label><label for="profile-goal">Моя цель<select class="select" id="profile-goal">${[['conversation','Поддерживать разговор'],['travel','Общаться в поездках'],['habit','Заниматься регулярно']].map(([v,t])=>`<option value="${v}" ${p().goal===v?'selected':''}>${t}</option>`).join('')}</select></label><label for="profile-pace">План занятий<select class="select" id="profile-pace">${[30,60,90].map(n=>`<option value="${n}" ${p().pace===n?'selected':''}>${n} учебных дней</option>`).join('')}</select></label></div><p class="small">Выбор сохраняется на этом устройстве. Первые 30 дней — основной курс. Дни 31–60 и 61–90 — авторское продолжение: разговорные задачи, свои ответы и чтение. В каждом этапе есть повторение. План не присваивает языковой уровень.</p></div></details>
   <details class="page-fold profile-progress" data-fold="profile:progress"><summary>История работы и проверка памяти</summary><div><dl><div><dt>Уроки основного курса</dt><dd>${e.completed.length} / 30</dd></div>${extension.totalDays?`<div><dt>Продолжение · дни 31–90</dt><dd>${extension.completedDays.length} / ${extension.totalDays}</dd></div>`:''}${extension.totalReadings?`<div><dt>Подготовленные задания по чтению</dt><dd>${extension.completedReadings.length} / ${extension.totalReadings}</dd></div>`:''}<div><dt>Практика за последние 7 дней</dt><dd>${active} ${active===1?'день':active>=2&&active<=4?'дня':'дней'}</dd></div><div><dt>Наборы после проверки через сутки</dt><dd>${e.retained.length} / 30</dd></div></dl><p class="small">Уроки и чтение показывают объём работы. Проверка через сутки подтверждает память трёх заданных фраз. Самостоятельную свободную речь эти числа не оценивают.</p>${due?`<div class="profile-repeat"><div><h3>Проверить память · день ${due}</h3><p>Вспомни три фразы без подсказки после паузы в сутки.</p></div><button type="button" class="btn" data-profile-action="mastery" data-profile-day="${due}">Проверить память ${icon('arrow-right')}</button></div>`:''}${p().showWeek?`<ol class="profile-week" aria-label="Учебные действия основного курса за семь дней">${e.week.map(d=>`<li><span>${esc(d.label)}</span><strong>${d.count}</strong></li>`).join('')}</ol><p class="small">Здесь записанные действия основного курса: один ответ считается один раз. День без записи — не провал.</p>`:''}${assistance(due?'Попробуй вспомнить без текста. Если трудно, разберём одну фразу.':'Выбери трудную реплику. Я помогу понять модель и попробовать снова.')}</div></details>
   <details class="page-fold profile-personal" data-fold="profile:personal"><summary>Что показывать в обзоре</summary><div>${[['showWeek','Показывать историю недели'],['showPractice','Предлагать короткое повторение'],['showLumo','Показывать подсказки Лумо']].map(([k,t])=>`<label class="profile-toggle"><input type="checkbox" data-profile-toggle="${k}" ${p()[k]?'checked':''}>${t}</label>`).join('')}</div></details>${footer()}</section>`;
 }
 function click(b){if(!b?.hasAttribute?.('data-profile-action'))return false;const kind=b.dataset.profileAction,day=Number(b.dataset.profileDay);if(kind==='profile')api.openProfile?.();else if(kind==='words'){if(validDay(day))api.openWords?.(day)}else if(kind==='pathway'){if(day>=31&&day<=90){state.pathway.selectedDay=day;save();openPractice('pathway')}}else if(kind==='lesson'){if(validDay(day))openLesson(day)}else if(['mission','workbook','mastery','pronunciation'].includes(kind)){if(validDay(day))openPractice(kind,day)}else if(kind==='review')openPractice('review');else return false;return true}
 function input(el){if(el?.id!=='profile-nickname')return false;state.profile.nickname=clean(el.value,40);save();return true}
 function change(el){if(el?.id==='profile-goal'){if(['conversation','travel','habit'].includes(el.value))state.profile.goal=el.value;save();return true}if(el?.id==='profile-pace'){if([30,60,90].includes(Number(el.value)))state.profile.pace=Number(el.value);save();toast('План сохранён на этом устройстве.');return true}if(['showWeek','showPractice','showLumo'].includes(el?.dataset?.profileToggle)){state.profile[el.dataset.profileToggle]=el.checked===true;save();return true}return input(el)}
 return {html,homeWidget,click,change,input,sanitize,evidence};
}};
