window.VamosProgress={create({state,data,save,toast,esc,icon,render}){
 let pending=null,message='';
 const ids=new Set(data.library.items.map(x=>x.id));
 const cardIds=new Set([...data.expanded.vocabulary.map(x=>'w:'+x.es),...data.expanded.lessons.flatMap(x=>x.examples.map(p=>'p:'+p.audio))]);
 const ratings=new Set(['independent','help','retry']);
 function html(){return `<section class="progress-transfer"><h2>Курс на другом устройстве</h2><p>Прогресс хранится в этом браузере. Чтобы перенести его на опубликованный сайт или телефон, сохрани файл здесь и импортируй там.</p><div class="transfer-actions"><button type="button" class="btn" data-backup-export>${icon('download')}Сохранить прогресс</button><label class="btn import-label">${icon('upload')}Выбрать файл<input type="file" id="backup-file" accept="application/json,.json"></label></div><p class="small">В файл входят твои заметки и самооценки. Голосовые записи в него не включаются. Файл обрабатывается на устройстве.</p>${pending?`<div class="import-preview"><p>В файле: ${pending.completed.length} выполненных дней, ${Object.keys(pending.cards).length} карточек. Добавим к текущему прогрессу; завершённые дни сохранятся.</p><button type="button" class="btn primary" data-backup-apply>Объединить прогресс</button><button type="button" class="btn quiet" data-backup-cancel>Отмена</button></div>`:''}${message?`<p role="status">${esc(message)}</p>`:''}</section>`}
 function sanitize(s){if(!s||typeof s!=='object'||Array.isArray(s))throw Error('В файле нет данных курса.');const out={completed:[...new Set((Array.isArray(s.completed)?s.completed:[]).filter(n=>Number.isInteger(n)&&n>=1&&n<=30))],cards:{},ratings:{},mistakes:{},checkpoints:{},sceneRatings:{},library:{favorites:[],known:[],difficult:[],notes:{}}};for(const [k,v] of Object.entries(s.cards||{})){if(cardIds.has(k)&&v&&Number.isFinite(v.due)&&v.due>=0&&v.due<=Date.now()+366*86400000)out.cards[k]={due:v.due,interval:Math.min(5,Math.max(0,Math.floor(Number(v.interval)||0))),attempts:Math.max(0,Math.min(100000,Math.floor(Number(v.attempts)||0)))};}for(let i=1;i<=30;i++){if(ratings.has(s.ratings?.[i]))out.ratings[i]=s.ratings[i];if(Number.isFinite(s.mistakes?.[i]))out.mistakes[i]=Math.max(0,Math.min(100000,Math.floor(s.mistakes[i])))}for(const key of [7,14,21,30]){const c=s.checkpoints?.[key];if(c&&ratings.has(c.rating))out.checkpoints[key]={rating:c.rating,checks:(Array.isArray(c.checks)?c.checks:[]).filter(x=>[0,1,2].includes(x)),date:Number.isFinite(c.date)?c.date:Date.now()}}for(const t of data.library.items.filter(x=>x.type==='text'))for(const role of ['А','Б']){const k=t.id+':'+role,v=s.sceneRatings?.[k];if(v&&ratings.has(v.rating))out.sceneRatings[k]={rating:v.rating,date:Number.isFinite(v.date)?v.date:Date.now()}}for(const key of ['favorites','known','difficult'])out.library[key]=[...new Set((Array.isArray(s.library?.[key])?s.library[key]:[]).filter(id=>ids.has(id)))];for(const [id,note] of Object.entries(s.library?.notes||{}))if(ids.has(id)&&typeof note==='string')out.library.notes[id]=note.slice(0,1000);return out}
 function click(b){if(b.hasAttribute('data-backup-export')){const blob=new Blob([JSON.stringify({format:'vamos-backup-v1',date:new Date().toISOString(),state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='vamos-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Файл прогресса сохранён.');return true}if(b.hasAttribute('data-backup-cancel')){pending=null;message='Импорт отменён.';render();return true}if(b.hasAttribute('data-backup-apply')&&pending){state.completed=[...new Set([...state.completed,...pending.completed])].sort((a,b)=>a-b);for(const [key,c] of Object.entries(pending.cards)){if(!state.cards[key])state.cards[key]=c;else state.cards[key].due=Math.min(state.cards[key].due,c.due)}for(const key of ['ratings','checkpoints','sceneRatings'])state[key]={...pending[key],...state[key]};for(const [k,n] of Object.entries(pending.mistakes))state.mistakes[k]=Math.max(state.mistakes[k]||0,n);for(const key of ['favorites','known','difficult'])state.library[key]=[...new Set([...state.library[key],...pending.library[key]])];state.library.notes={...pending.library.notes,...state.library.notes};pending=null;message='Прогресс объединён. Текущие заметки и настройки сохранены.';save();render();return true}return false}
 async function change(el){if(el.id!=='backup-file')return;const f=el.files?.[0];if(!f)return;try{if(f.size>1048576)throw Error('Файл слишком большой. Нужен JSON прогресса до 1 МБ.');const d=JSON.parse(await f.text());if(d.format!=='vamos-backup-v1')throw Error('Выбери файл, сохранённый кнопкой «Сохранить прогресс».');pending=sanitize(d.state);message='Проверь данные перед объединением.'}catch(e){pending=null;message='Не удалось прочитать файл. '+(e instanceof SyntaxError?'Проверь, что это JSON прогресса.':e.message)}render();document.querySelector('.progress-transfer')?.scrollIntoView({block:'start'})}
 return {html,click,change};
}};
