/* Opt-in voice archive. Blob audio stays in IndexedDB and is excluded from JSON backups. */
window.VamosRecordings={create({esc,icon,footer,render,toast,active,data={},playButton=()=>'',audioCredit=()=>'',audioControls=()=>'',audioStatus=()=>''}){
 let db=null,items=[],status='Открываем локальный архив…',loaded=false,urls=new Map(),selected=[],saving=false;
 const max=8,maxBytes=8*1024*1024;
 // Only originals in the supplied course catalogue can be attached to a voice attempt.
 const models=new Map();for(const source of [data.expanded?.audio,data.wordAudio?.clips])for(const [id,a]of Object.entries(source||{}))if(a&&typeof a.text==='string'&&a.text&&typeof a.file==='string')models.set(id,{audio:id,es:a.text});
 const model=r=>typeof r?.audio==='string'?models.get(r.audio):null;
 function capture(meta={}){const r={day:Math.min(30,Math.max(1,Number(meta.day)||1)),label:String(meta.label||'Моя устная попытка').slice(0,140),context:String(meta.context||'').slice(0,100)};if(Number.isInteger(meta.contentDay)&&meta.contentDay>=1&&meta.contentDay<=30)r.contentDay=meta.contentDay;const m=model(meta);if(m){r.audio=m.audio;r.es=m.es;}return r;}
 function sourceHTML(r){const m=model(r);if(!m)return '';return `<section class="voice-original" data-line-audio="${esc(m.audio)}"><h3>Образец носителя</h3><p lang="es" class="voice-model-caption">${esc(m.es)}</p>${playButton(m.audio,'Слушать точный образец: '+m.es,true)}<details class="voice-source"><summary>Темп и источник записи</summary>${audioControls()}${audioCredit(m)}</details></section>`;}

 function revoke(){for(const url of urls.values())URL.revokeObjectURL(url);urls.clear()}
 function transaction(mode,action){return new Promise((resolve,reject)=>{if(!db){reject(Error('Архив недоступен в этом браузере.'));return}const tx=db.transaction('clips',mode),store=tx.objectStore('clips');let result;const request=action(store);if(request)request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||Error('Не удалось сохранить запись.'));tx.onabort=()=>reject(tx.error||Error('Операция отменена.'))})}
 async function refresh(){try{const records=await transaction('readonly',s=>s.getAll());revoke();items=records.filter(r=>r&&r.blob instanceof Blob&&r.blob.size<=maxBytes&&typeof r.id==='string'&&typeof r.label==='string').sort((a,b)=>b.created-a.created);for(const r of items)urls.set(r.id,URL.createObjectURL(r.blob));selected=selected.filter(id=>urls.has(id));status=''}catch{status='Не удалось прочитать архив. Текущую запись можно скачать под микрофоном.'}loaded=true;if(active())render()}
 try{const request=indexedDB.open('vamos-voice-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('clips',{keyPath:'id'});request.onsuccess=()=>{db=request.result;db.onversionchange=()=>{db.close();db=null;status='Архив обновлён в другой вкладке. Обнови страницу.'};refresh()};request.onerror=()=>{loaded=true;status='Браузер не разрешил локальный архив. Текущую запись можно скачать.';if(active())render()};request.onblocked=()=>{status='Закрой другую вкладку курса, чтобы открыть архив.';if(active())render()}}catch{loaded=true;status='Локальный архив недоступен. Текущую запись можно скачать.'}
 async function save(blob,meta={}){if(saving)return false;if(!db){toast('Архив пока недоступен. Скачай текущую запись.');return false}if(!(blob instanceof Blob)||!blob.size||blob.size>maxBytes){toast('Не удалось сохранить: запись пустая или больше 8 МБ.');return false}const captured=capture(meta);saving=true;try{const count=await transaction('readonly',s=>s.count());if(count>=max){toast('В архиве восемь записей. Удали одну, чтобы сохранить новую.');return false}const created=Date.now(),id=crypto.randomUUID?.()||created+'-'+Math.random().toString(36).slice(2);await transaction('readwrite',s=>s.add({id,created,...captured,blob}));await refresh();toast('Голос сохранён только на этом устройстве.');return true}catch{toast('Браузер не сохранил запись. Скачай её перед выходом.');return false}finally{saving=false}}
 function clip(r,compare=false){const url=urls.get(r.id);return `<article class="voice-slip ${compare?'voice-compare':''}"><h2>${esc(r.label)}</h2><p class="record-meta">День ${r.day}${Number.isInteger(r.contentDay)&&r.contentDay>=1&&r.contentDay<=30&&r.contentDay!==r.day?' · тема '+r.contentDay:''} · ${new Date(r.created).toLocaleDateString('ru')}</p><div class="voice-model-pair ${model(r)?'has-original':'self-only'}">${sourceHTML(r)}<section class="voice-self"><h3>Моя попытка</h3><audio controls preload="none" src="${esc(url)}" aria-label="${esc(r.label)}"></audio></section></div>${compare?'':`<div class="controls"><button type="button" class="btn quiet" data-voice-compare="${esc(r.id)}" aria-pressed="${selected.includes(r.id)}">${selected.includes(r.id)?'Выбрано':'Сравнить'}</button><a class="btn quiet" href="${esc(url)}" download="vamos-day-${r.day}.${r.blob.type.includes('mp4')?'m4a':'webm'}">${icon('download')}Скачать</a><button type="button" class="btn quiet" data-voice-delete="${esc(r.id)}">${icon('trash-2')}Удалить</button></div>`}</article>`}
 function html(){return `<section class="reading record-archive"><h1>Услышь свою разницу</h1><p class="page-intro">Сохраняй удачные и трудные попытки. Слушай образец носителя рядом со своей попыткой, если её источник сохранён. Выбери одно отличие: гласную, ударение или паузу.</p><p class="note">До восьми записей, только в этом браузере. Добавляй запись кнопкой «В архив» после остановки микрофона. В файле прогресса аудио нет; перед сменой устройства скачай нужные записи. Архив не измеряет акцент или уровень.</p>${status?`<p role="status">${esc(status)}</p>`:''}${items.some(r=>model(r))?audioStatus():''}${selected.length===2?`<div class="controls"><button type="button" class="btn quiet" data-voice-clear>К списку записей</button></div><section class="voice-pair" aria-label="Сравнение двух своих записей">${selected.map(id=>clip(items.find(r=>r.id===id),true)).join('')}</section><p>Прослушай по очереди и сравни одно отличие: гласную, ударение или паузу. Если фразы разные, сравни каждую со своим образцом.</p>`:''}${!items.length&&loaded?`<div class="voice-empty"><h2>Здесь появится твой голос</h2><p>Начни с короткой собственной фразы в практике. Сохранение всегда по твоему нажатию.</p><button type="button" class="btn primary" data-practice-open="pronunciation">Сказать и сравнить ${icon('mic')}</button></div>`:items.filter(r=>selected.length!==2||!selected.includes(r.id)).map(r=>clip(r)).join('')}${footer()}</section>`}
 function click(b){if(b.hasAttribute?.('data-voice-clear')){selected=[];render();return true}if(b.dataset.voiceCompare){const id=b.dataset.voiceCompare;if(!urls.has(id))return true;if(selected.includes(id))selected=selected.filter(x=>x!==id);else{if(selected.length===2)selected.shift();selected.push(id)}render();return true}if(b.dataset.voiceDelete){const id=b.dataset.voiceDelete;if(!urls.has(id))return true;transaction('readwrite',s=>s.delete(id)).then(refresh).then(()=>toast('Запись удалена с этого устройства.')).catch(()=>toast('Не удалось удалить запись.'));return true}return false}
 window.addEventListener('pagehide',()=>{revoke();db?.close()});
 return {html,click,save,stop:()=>document.querySelectorAll('.record-archive audio').forEach(a=>a.pause())};
}};
