/* Scoped caches never touch another GitHub Pages project. Native files stay unmodified. */
'use strict';
const BASE=new URL('./',self.location.href),PREFIX='vamos-'+encodeURIComponent(BASE.pathname)+'-',SHELL=PREFIX+'shell-v15-1',MEDIA=PREFIX+'audio';
const FILES=['./','index.html','course.css','course-foundation.css','course-v3.css','course-v4.css','course-v5.css','course-data.js','course.js','library.js','coach.js','progress.js','learning.js','speech.js','native.js','drills.js','mastery.js','adaptive.js','navigation.js','navigation.css','course-v7.css','course-v8.css','goals.js','studio.js','missions.js','recordings.js','workbook.js','course-v9.css','course-v10.css','alegreya.css','course-v11.css','experience.js','experience.css','adult.css','manifest.webmanifest','assets/plaza.svg','assets/alegreya-latin.woff2','assets/alegreya-cyrillic.woff2','assets/onest-latin.woff2','assets/onest-cyrillic.woff2','assets/lucide.min.js','assets/lumo-poses.webp','assets/app-icon.svg','assets/app-icon-192.png','assets/app-icon-512.png','assets/audio/ATTRIBUTION.json','assets/audio/README.txt'];
FILES.push('repair.js','repair.css','bridge-review.js');
FILES.push('day-compass.js','day-compass.css','cafe.css','assets/lumo-cafe-v15.webp','assets/patio-tile-v15.svg');
FILES.push('videos.js','focus-home.js','focus-home.css','lesson-focus.css');
FILES.push(...["profile.js", "profile.css", "pathway.js", "pathway.css", "identity.js", "identity.css", "welcome.js", "journey-ui.css", "manifest-lumo-wave.webmanifest", "manifest-lumo-joy.webmanifest", "manifest-lumo-think.webmanifest", "manifest-lumo-proud.webmanifest", "assets/lumo-welcome-v13.webp", "assets/app-icon-lumo-192.png", "assets/app-icon-lumo-512.png", "assets/app-icon-lumo-wave-192.png", "assets/app-icon-lumo-wave-512.png", "assets/app-icon-lumo-joy-192.png", "assets/app-icon-lumo-joy-512.png", "assets/app-icon-lumo-think-192.png", "assets/app-icon-lumo-think-512.png", "assets/app-icon-lumo-proud-192.png", "assets/app-icon-lumo-proud-512.png", "assets/favicon-lumo-wave.png", "assets/favicon-lumo-joy.png", "assets/favicon-lumo-think.png", "assets/favicon-lumo-proud.png"]);
self.addEventListener('install',e=>e.waitUntil(caches.open(SHELL).then(c=>c.addAll(FILES.map(p=>new URL(p,BASE).href)))));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const name of await caches.keys())if(name.startsWith(PREFIX+'shell-')&&name!==SHELL)await caches.delete(name);await self.clients.claim()})()));
self.addEventListener('message',e=>{if(e.data?.type==='ACTIVATE')self.skipWaiting()});
async function range(response,header){const bytes=await response.arrayBuffer(),size=bytes.byteLength,m=/^bytes=(\d*)-(\d*)$/.exec(header);if(!m)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${size}`}});let start=m[1]?Number(m[1]):Math.max(0,size-Number(m[2])),end=m[1]?(m[2]?Number(m[2]):size-1):size-1;end=Math.min(end,size-1);if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>end||start<0||start>=size)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${size}`}});return new Response(bytes.slice(start,end+1),{status:206,headers:{'Content-Type':response.headers.get('Content-Type')||'audio/mpeg','Content-Length':String(end-start+1),'Content-Range':`bytes ${start}-${end}/${size}`,'Accept-Ranges':'bytes'}})}
self.addEventListener('fetch',e=>{const req=e.request,url=new URL(req.url);if(req.method!=='GET'||url.origin!==BASE.origin||!url.pathname.startsWith(BASE.pathname))return;const audio=/\/assets\/audio\/\d+\.mp3$/.test(url.pathname);e.respondWith((async()=>{const cache=await caches.open(audio?MEDIA:SHELL),canonical=new URL(url.href);if(req.mode==='navigate')canonical.search='';let cached=await cache.match(canonical.href);if(audio&&cached&&req.cache!=='reload')return req.headers.has('range')?range(cached,req.headers.get('range')):cached;try{const response=await fetch(req);if(response.ok&&response.status===200){await cache.put(canonical.href,response.clone())}return response}catch{if(cached)return cached;if(req.mode==='navigate')return await cache.match(new URL('./',BASE).href)||await cache.match(new URL('index.html',BASE).href)||Response.error();return Response.error()}})())});

self.addEventListener("notificationclick",e=>{e.notification.close();e.waitUntil((async()=>{const all=await self.clients.matchAll({type:"window",includeUncontrolled:true});const found=all.find(c=>{const u=new URL(c.url);return u.origin===BASE.origin&&u.pathname.startsWith(BASE.pathname)});if(found){await found.focus();return}await self.clients.openWindow(new URL("./?view=home",BASE).href)})())});
